### ISSUE TITLE
Why do you need to handle server.httpServer in server.listen?. on

### ISSUE THREAD

**Issue by wChenonly** [svitejs/vite-plugin-qrcode#114]
### Describe the problem

I tried to use only server.httpServer? .on is also ok.

server.httpServer?.on('listening', () => {
	setTimeout(() => logQrcode(server, options), 0);
});

I see that it was modified https://github.com/svitejs/vite-plugin-qrcode/commit/67588a808cac0b12be41a92567f568a2e12a1541 this commit, I don't quite understand this meaning, thank the author for taking the time to answer it

### Describe the proposed solution

If there is no such problem now, can it be removed so that it is more concise?

### Alternatives considered

no

### Importance

nice to have

**Comment by bluwy** [comment]
It's so we only log the qrcode on initial startup and not on subsequent restarts. If you remove that, the qrcode will always get logged on restarts which we want to avoid.

**Comment by wChenonly** [comment]
> It's so we only log the qrcode on initial startup and not on subsequent restarts. If you remove that, the qrcode will always get logged on restarts which we want to avoid.

By reboot you mean hmr?

**Comment by bluwy** [comment]
Not exactly. Only when the server restarts e.g. when you press the "r" CLI shortcut, or when you call [`server.restart()`](https://github.com/vitejs/vite/blob/ec9d2e779d4b8d785c648430594d534d461d6639/packages/vite/src/node/server/index.ts#L496-L505) programatically.

**Comment by wChenonly** [comment]
> Not exactly. Only when the server restarts e.g. when you press the "r" CLI shortcut, or when you call [`server.restart()`](https://github.com/vitejs/vite/blob/ec9d2e779d4b8d785c648430594d534d461d6639/packages/vite/src/node/server/index.ts#L496-L505) programmatically.

Thank you very much, I understand.
