### ISSUE TITLE
Show only the qr of a network

### ISSUE THREAD

**Issue by ediaz2** [svitejs/vite-plugin-qrcode#28]
### Describe the problem

It shows the qr of all the networks, to access local from the mobile I have to scroll
![image](https://user-images.githubusercontent.com/8389931/158943983-bf477d0f-035d-4591-b368-e067415462c1.png)

### Describe the proposed solution

Pass an option as a parameter indicating the key to show optionally
![image](https://user-images.githubusercontent.com/8389931/158944431-bee01fcd-229e-45c8-a796-13a169f369cf.png)
```ts
// vite.config.js
import { qrcode } from 'vite-plugin-qrcode';

export default defineConfig({
  plugins: [
    qrcode({ keyNetwork: 0 }) // network key to display qr
  ]
});
```

```ts
function logQrcode(server: ViteDevServer, { keyNetwork }: { keyNetwork?: number }): void {
  const networkUrls = getNetworkUrls(server);

  if (networkUrls.length === 0) return;

  const { info } = server.config.logger;

  info('  Visit page on mobile:');
  /**
  * Show only one network
  */
  if (typeof keyNetwork === 'number') {
    qr.generate(networkUrls[keyNetwork], { small: true }, (result) => {
      info(`  ${cyan(networkUrls[keyNetwork])}\n  ${result.replace(/\n/g, '\n  ')}`);
    });
  } else {
    // eslint-disable-next-line no-restricted-syntax
    for (const url of networkUrls) {
      qr.generate(url, { small: true }, (result) => {
        info(`  ${cyan(url)}\n  ${result.replace(/\n/g, '\n  ')}`);
      });
    }
  }
}

```
![image](https://user-images.githubusercontent.com/8389931/158946489-652056b6-48d9-4145-b252-5a46949753fa.png)

### Alternatives considered

Use a `firstNetwork : boolean` parameter, so that only the first is displayed, although I don't know if they all get the same order

### Importance

would make my life easier

**Comment by dominikg** [comment]
using index would be brittle :thinking:  maybe a custom filter function added here 
https://github.com/svitejs/vite-plugin-qrcode/blob/ed2f4e0d1a7a3fc6060ab3f4df8d0ffa90d51b70/packages/vite-plugin-qrcode/src/index.ts#L64

maybe we should also filter on vite server address if it wasn't started with 0.0.0.0

**Comment by ediaz2** [comment]
The local network appears when the `server.host` has the value `0.0.0.0` or `true`;
If it is filtered, these 2 cases should be taken into account.

I'm going to review the `vite` documentation more, I use this plugin daily to review the mobile view.
Thanks for your time.

**Comment by bluwy** [comment]
I think it makes sense to introduce a filter function too, something like:
```js
// vite.config.js
import { qrcode } from 'vite-plugin-qrcode';

export default defineConfig({
  plugins: [
    qrcode({
      filter: (url, i) => i === 0 // or match by url incase index changes
    })
  ]
});
```

**Comment by bluwy** [comment]
There's now a [`filter` option](https://github.com/svitejs/vite-plugin-qrcode/tree/main/packages/vite-plugin-qrcode#filter) that you can use to filter for a specific IP.

**Comment by ediaz2** [comment]
Thanks 😊
