### ISSUE TITLE
size

### ISSUE THREAD

**Issue by geekact** [svitejs/vite-plugin-qrcode#84]
### Describe the problem

Actually, the qrcode size is too large in terminal.

### Describe the proposed solution

Consider to provide an option
```javascript
qrcode({
  size: 50
});
```

### Alternatives considered

:)

### Importance

nice to have

**Comment by geekact** [comment]
Alternative, rename PluginOptions to `QrcodeOptions` would be better.

**Comment by bluwy** [comment]
We're already printing it small by default:

https://github.com/svitejs/vite-plugin-qrcode/blob/f979084ac32dbccb04e09482df16fa210fb03080/packages/vite-plugin-qrcode/src/index.ts#L42

Going any smaller it might not be scannable as the terminal doesn't have the glyphs to print in high resolution.

**Comment by bluwy** [comment]
Closing as it's not possible at the moment.
