### ISSUE TITLE
qr is not square

### ISSUE THREAD

**Issue by nicolaeClichici** [svitejs/vite-plugin-qrcode#90]
### Describe the bug

Hi! Qr code have height bigger than width.
I use webstorm 2022.2.3, vite 4.0, vite-plugin-qrcode 0.2.1

### Reproduction

![image](https://user-images.githubusercontent.com/113600769/220538445-a3751034-afcf-4914-a151-7d645741610b.png)

### System Info

```shell
-
```

### Severity

annoyance

**Comment by bluwy** [comment]
That's because the terminal have spacing between each line, there's not really much we can do as the styling is controlled by the terminal.

**Comment by nicolaeClichici** [comment]
Ok, thx
